### ISSUE TITLE
syntax error in expression (error token is "4

### ISSUE THREAD

**Issue by permem** [DazzyWalkman/oplxc4pve#4]
Hi,

I tried to upgrade Openwrt from existing  22.03.2 to 22.03.3 using the following procedure:

root@pve:~/lxd-openwrt-simplified# wget https://downloads.openwrt.org/releases/22.03.3/targets/x86/64/openwrt-22.03.3-x86-64-rootfs.tar.gz

root@pve:~/lxd-openwrt-simplified# ./build_cust.sh openwrt-22.03.3-x86-64-rootfs.tar.gz plain
cd ../oplxc4pve/
cp ../lxd-openwrt-simplified/bin/OpenWrt-22.03.3-r20028-43d71ad93e-x86_64-plain.tar.gz .
./opct.sh up 104 101 OpenWrt-22.03.3-r20028-43d71ad93e-x86_64-plain.tar.gz

I received the following error:

Sat Jan 14 07:13:39 CET 2023 upgrade: Saving config files...
Old CT conf backup completed.
./opct.sh: line 158: 4
4
4: syntax error in expression (error token is "4
4")

I have the latest version of oplxc4pve, lxd-openwrt-simplified and Proxmox 7.3-4.

Please advice.

**Comment by permem** [comment]
It seems the problem was on my side. I created new LXC and restored configurations manually from
the running Openwrt.
Then I tried again using oplxc4pve on snapshot without issues.

**Comment by DazzyWalkman** [comment]
I've followed your steps, and failed to reproduce the same result.

Fortunately, the error message has provided enough information.  

Background:
The value of "cores", has to be integer by the pct.conf spec, and there is always a space after ":" for each value in the pve generated conf file. The pve will always format the conf file back to this standard formatting whenever the respective instance is shutdown.  

Probably you might have manually edited your 104.conf, insert or delete some char around cores value, during 104 was running. The opct.sh was unable to extract integer value from such editing.  Then came this error. 

Later I'll try to improve the robustness for such use case.

**Comment by DazzyWalkman** [comment]
Closed with 1c344805ef45485710ae25724389c6fca9ec4353
