### ISSUE TITLE
Zapret aren't working

### ISSUE THREAD

**Issue by rapdodge** [DazzyWalkman/oplxc4pve#6]
I'm adding
```
system("modprobe nfnetlink_queue");
```
And others
![image](https://user-images.githubusercontent.com/33513626/232206359-d0af07c4-7091-4cae-a7db-6976617e1e98.png)

![image](https://user-images.githubusercontent.com/33513626/232202841-e576f9ec-ef5d-4221-b463-39b942231ef3.png)

![image](https://user-images.githubusercontent.com/33513626/232205343-cf091ae0-73bb-436a-a28f-9e434577b811.png)

Any ideas for this?

About zapret project -> [here](https://github.com/bol-van/zapret/blob/master/docs/readme.eng.md)

**Comment by rapdodge** [comment]
Fixed

https://github.com/bol-van/zapret/issues/140#issuecomment-1509995374

Maybe you can adding modprobe things down below to the hookscript
```
#needed by zapret
system("modprobe nf_conntrack");
system("modprobe nf_defrag_ipv4");
system("modprobe nf_defrag_ipv6");
system("modprobe nf_flow_table");
system("modprobe nf_flow_table_inet");
system("modprobe nf_log_ipv4");
system("modprobe nf_log_ipv6");
system("modprobe nf_nat");
system("modprobe nf_reject_ipv4");
system("modprobe nf_reject_ipv6");
system("modprobe nf_tables");
system("modprobe nft_objref");
system("modprobe nfnetlink");
system("modprobe nfnetlink_queue");
system("modprobe nft_chain_nat");
system("modprobe nft_ct");
system("modprobe nft_fib");
system("modprobe nft_fib_inet");
system("modprobe nft_fib_ipv4");
system("modprobe nft_fib_ipv6");
system("modprobe nft_flow_offload");
system("modprobe nft_hash");
system("modprobe nft_limit");
system("modprobe nft_log");
system("modprobe nft_masq");
system("modprobe nft_nat");
system("modprobe nft_numgen");
system("modprobe nft_objref");
system("modprobe nft_queue");
system("modprobe nft_quota");
system("modprobe nft_redir");
system("modprobe nft_reject");
system("modprobe nft_reject_inet");
system("modprobe nft_reject_ipv4");
system("modprobe nft_reject_ipv6");
```

**Comment by rapdodge** [comment]
![image](https://user-images.githubusercontent.com/33513626/232315705-2f5071b5-2f0b-4887-b3cb-fd8cf229f03d.png)

![image](https://user-images.githubusercontent.com/33513626/232315708-100f094e-0274-47a8-b734-3b53c70bfda3.png)

Hmmm... After enabling FUSE and Nesting, there is error, just disabling it, and it's fixed... But, the modprobe are still the same...

Edit:
nevermind, still crashed... idk it's because the build, or, error because importing all the modprobe...

**Comment by DazzyWalkman** [comment]
Unfortunately, I have little knowledge about Zapret, and there are too many usecases to be included in the hookscript example.
I can only share with you some generic experiences.
Usually I get the kernel module dependency information from the makefile of the certain OpenWrt package, then modprobe the needed ones. However, in your case, there are none of such makefile. Then you need to try figure it out.

I suggest you first config a working build in a full virtual machine or privileged lxc instance to ensure it indeed works, and take note of the output of lsmod and item list of the /dev. And then fire up an unprivileged lxc with the same network topology, modprobe and create device item according to the previous note. You may also have to take care of the SYS_CAP thing.  
Possibly you can set up the unprivileged lxc instance to meet the minimum requirements in such procedure.  

Generally speaking, modprobing more than enough kmods won't do much harm other than waste of system resource.

**Comment by rapdodge** [comment]
> Unfortunately, I have little knowledge about Zapret, and there are too many usecases to be included in the hookscript example.
> I can only share with you some generic experiences.
> Usually I get the kernel module dependency information from the makefile of the certain OpenWrt package, then modprobe the needed ones. However, in your case, there are none of such makefile. Then you need to try figure it out.
> 
> I suggest you first config a working build in a full virtual machine or privileged lxc instance to ensure it indeed works, and take note of the output of lsmod and item list of the /dev. And then fire up an unprivileged lxc with the same network topology, modprobe and create device item according to the previous note. You may also have to take care of the SYS_CAP thing.  
> Possibly you can set up the unprivileged lxc instance to meet the minimum requirements in such procedure.  
> 
> Generally speaking, modprobing more than enough kmods won't do much harm other than waste of system resource.  

Hello there, yeah, I've tried the OpenWrt qemu, and then capture the lsmod output, and then I'm saving all nftables related modprobe, and adding it on unprivileged container, and it's working now...

Let's see if i can remove some of it, since nfqws are just needing queue things...

Best regards,

**Comment by rapdodge** [comment]
https://github.com/bol-van/zapret/issues/140#issuecomment-1521092392
